### ISSUE TITLE
程序问题

### ISSUE THREAD

**Issue by 01SHENyankun** [BoyuanJiang/context_encoder_pytorch#20]
![20210922144704](https://user-images.githubusercontent.com/84694608/134295833-d3e46fe2-5646-4673-8525-295a9512f9bf.png)

**Comment by R1ckLou** [comment]
请问你解决了吗？

**Comment by 01SHENyankun** [comment]
> 请问你解决了吗？
没有，我现在连环境都没配好，你配好了嘛

**Comment by 01SHENyankun** [comment]
> 请问你解决了吗？

能不能给个联系方式

**Comment by R1ckLou** [comment]
> > 请问你解决了吗？
> > 没有，我现在连环境都没配好，你配好了嘛

我就遇到这个问题 一直解决不了 squeeze也不行

**Comment by R1ckLou** [comment]
> > 请问你解决了吗？
> 
> 能不能给个联系方式
你的联系方式是？

**Comment by 01SHENyankun** [comment]
> > > 请问你解决了吗？
> > > 没有，我现在连环境都没配好，你配好了嘛
> 
> 我就遇到这个问题 一直解决不了 squeeze也不行

好吧

**Comment by 01SHENyankun** [comment]
> > > 请问你解决了吗？
> > 
> > 
> > 能不能给个联系方式
> > 你的联系方式是？

2635505974
