### ISSUE TITLE
strange results on lfw dataset

### ISSUE THREAD

**Issue by micklexqg** [BoyuanJiang/context_encoder_pytorch#7]
I trained on lfw dataset with the code, but the result is very strange:
![image](https://user-images.githubusercontent.com/13776012/34323939-69da851c-e898-11e7-9ed4-565a1f219910.png)
![image](https://user-images.githubusercontent.com/13776012/34323943-7b8ca308-e898-11e7-922d-51930b5775ea.png)
have you ever tried on lfw?

**Comment by BoyuanJiang** [comment]
No,and I'm not sure why the edges are so strange.

**Comment by micklexqg** [comment]
thanks for reply. if you plan to try on it, please tell the result. I want to know where I make mistakes.
does torch must be installed on linux?

**Comment by BoyuanJiang** [comment]
do you mean pytorch?you can also insteal it on win or mac too.

**Comment by micklexqg** [comment]
I mean torch, which is for lua.

**Comment by BoyuanJiang** [comment]
That I have only installed on the linux,so not sure if can install on other platforms.
